### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by samkas125** [ADJ46/Mlminiprj#1]
Hi, thanks a lot for uploading this. I ran it locally and was able to run it. But when I ran it with row 140 of the csv file, the predicted area is coming to be 1 instead of 0.36. I tried with a couple of my own values as well and it always came out to be 0 or 1. In your testing were you able to get the model to predict the right areas?

**Comment by ADJ46** [comment]
hello
The model predicts the probability so it will only give 0 and 1 as the output.
